name: build-bot
on:
  push:

jobs:
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate variables
        id: vars
        run: |
          echo "date=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build image
        run: |
          docker build \
            --tag ghcr.io/${{ github.repository_owner }}/tag-bot:${{ steps.vars.outputs.date }} \
            --tag ghcr.io/${{ github.repository_owner }}/tag-bot:latest \
            bot

      - name: Push to ghcr
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/tag-bot:${{ steps.vars.outputs.date }}
          docker push ghcr.io/${{ github.repository_owner }}/tag-bot:latest
